#!/usr/bin/env python3
"""extract_scs_tree.py — Extract standardized scene tree from SCS metadata.

Reads HOOPS SCS metadata JSON files (generated by dwg_to_scs or HOOPS tools)
and produces a standardized structure tree JSON for comparison with the
self-developed DWG parser's SceneGraph output.

Usage:
  python3 scripts/extract_scs_tree.py <scs_metadata.json> <output.json>
  python3 scripts/extract_scs_tree.py scs_dwg/Drawing2.scs.metadata.json /tmp/Drawing2_scs_tree.json

Input:  scs_dwg/*.scs.metadata.json (HOOPS SCS metadata with node hierarchy)
Output: Standardized JSON with scene tree, node statistics, and bounding boxes.
"""

import json
import math
import sys
from collections import Counter, defaultdict
from pathlib import Path


def load_json(path: str) -> dict:
    for enc in ('utf-8', 'gb2312', 'gbk', 'latin-1'):
        try:
            with open(path, encoding=enc) as f:
                return json.load(f)
        except UnicodeDecodeError:
            continue
    raise ValueError(f"Could not decode {path} with any known encoding")


def parse_vec3(s: str) -> tuple:
    """Parse 'x,y,z' string to (x, y, z) floats."""
    parts = s.split(',')
    return tuple(float(p) for p in parts[:3])


def classify_node(name: str, depth: int, child_count: int) -> str:
    """Classify a HOOPS node by its name and position in the tree."""
    if not name:
        return 'Unknown'

    upper = name.upper()

    # Root/model nodes
    if depth == 0:
        return 'ModelRoot'

    # Paper space / layout detection
    if 'MODEL' in upper and ('SPACE' in upper or '空间' in name):
        return 'ModelSpace'
    if 'PAPER' in upper and ('SPACE' in upper or '空间' in name):
        return 'PaperSpace'

    # Layout names often contain "Layout" or specific sheet names
    if 'LAYOUT' in upper or '布局' in name:
        return 'Layout'
    if 'SHEET' in upper or '图框' in name:
        return 'Sheet'

    # Viewport
    if 'VIEWPORT' in upper or '视口' in name:
        return 'Viewport'

    # Block definitions (anonymous blocks start with *)
    if name.startswith('*'):
        if name.startswith('*D'):
            return 'AnonymousDimBlock'
        if name.startswith('*U'):
            return 'AnonymousGroupBlock'
        if name.startswith('*X'):
            return 'AnonymousXrefBlock'
        return 'AnonymousBlock'

    # Named blocks with common CAD patterns
    if upper.startswith('BLOCK_') or upper.startswith('BLK_'):
        return 'Block'

    # Title block patterns
    if 'TITLE' in upper or '标题' in name:
        return 'TitleBlock'
    if 'BORDER' in upper or '图框' in name:
        return 'Border'

    # Caterpillar/chain pattern (HOOPS internal grouping for DWG layouts)
    if 'CATERPILLAR' in upper:
        return 'LayoutGroup'

    # If node has many children, it's likely a container
    if child_count > 5:
        return 'Container'

    # Default: treat as entity group or component
    return 'Component'


def build_tree(nodes: list) -> dict:
    """Build a tree structure from flat node list with key/parent_key."""
    # Index nodes by key
    node_map = {}
    for i, node in enumerate(nodes):
        key = node.get('key', str(i))
        node_map[key] = node

    # Build children lists
    children_map = defaultdict(list)
    root_nodes = []

    for node in nodes:
        key = node.get('key', '')
        parent_key = node.get('parent_key', '')

        if not parent_key or parent_key not in node_map:
            root_nodes.append(node)
        else:
            children_map[parent_key].append(node)

    def build_subtree(node: dict, depth: int) -> dict:
        key = node.get('key', '')
        name = node.get('name', '')
        children = children_map.get(key, [])

        # Parse bounding box
        bbox_min = None
        bbox_max = None
        bbox_center = None
        bbox_size = None

        if node.get('standard_bbox_valid'):
            try:
                bbox_min = list(parse_vec3(node['standard_bbox_min']))
                bbox_max = list(parse_vec3(node['standard_bbox_max']))
            except (ValueError, KeyError):
                pass

        if node.get('minimum_bbox_valid'):
            try:
                bbox_center = list(parse_vec3(node['minimum_bbox_center']))
                bbox_size = list(parse_vec3(node['minimum_bbox_size']))
            except (ValueError, KeyError):
                pass

        node_type = classify_node(name, depth, len(children))

        result = {
            'key': key,
            'name': name,
            'type': node_type,
            'depth': depth,
            'persistent_id': node.get('persistent_id', 0),
            'unit': node.get('unit', 0),
        }

        if bbox_min and bbox_max:
            result['bbox_min'] = bbox_min
            result['bbox_max'] = bbox_max
        if bbox_center and bbox_size:
            result['bbox_center'] = bbox_center
            result['bbox_size'] = bbox_size

        if children:
            result['children'] = [
                build_subtree(child, depth + 1)
                for child in sorted(children, key=lambda n: n.get('key', ''))
            ]

        return result

    if len(root_nodes) == 1:
        return build_subtree(root_nodes[0], 0)
    else:
        # Multiple roots — wrap in synthetic root
        return {
            'key': '__root__',
            'name': '__root__',
            'type': 'SyntheticRoot',
            'depth': 0,
            'children': [
                build_subtree(r, 1) for r in sorted(root_nodes, key=lambda n: n.get('key', ''))
            ]
        }


def compute_tree_stats(tree: dict) -> dict:
    """Compute statistics from the tree structure."""
    stats = {
        'total_nodes': 0,
        'max_depth': 0,
        'type_counts': Counter(),
        'leaf_count': 0,
        'total_bbox_min': [float('inf'), float('inf'), float('inf')],
        'total_bbox_max': [float('-inf'), float('-inf'), float('-inf')],
    }

    def walk(node: dict):
        stats['total_nodes'] += 1
        depth = node.get('depth', 0)
        stats['max_depth'] = max(stats['max_depth'], depth)
        stats['type_counts'][node.get('type', 'Unknown')] += 1

        has_children = 'children' in node and len(node['children']) > 0
        if not has_children:
            stats['leaf_count'] += 1

        # Aggregate bounding box
        if 'bbox_min' in node:
            for i in range(3):
                stats['total_bbox_min'][i] = min(stats['total_bbox_min'][i], node['bbox_min'][i])
        if 'bbox_max' in node:
            for i in range(3):
                stats['total_bbox_max'][i] = max(stats['total_bbox_max'][i], node['bbox_max'][i])

        for child in node.get('children', []):
            walk(child)

    walk(tree)

    # Clean up inf/-inf
    if stats['total_bbox_min'][0] == float('inf'):
        stats['total_bbox_min'] = None
        stats['total_bbox_max'] = None

    stats['type_counts'] = dict(stats['type_counts'])
    return stats


def extract_layer_names_from_nodes(nodes: list) -> list:
    """Try to extract layer-like groupings from node names."""
    # In HOOPS SCS for DWG, layers are often represented as top-level groups
    # under the model root. Look for patterns.
    layer_candidates = set()
    for node in nodes:
        name = node.get('name', '')
        # Skip internal/Caterpillar groups
        if not name or 'CATERPILLAR' in name.upper():
            continue
        # Layer-like names: alphanumeric, may contain hyphens/underscores
        # Skip obviously non-layer names
        if name.startswith('*') or name.startswith('__'):
            continue
        layer_candidates.add(name)
    return sorted(layer_candidates)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <scs_metadata.json> <output.json>")
        print(f"\nExtracts standardized scene tree from SCS metadata for comparison.")
        sys.exit(2)

    input_path = sys.argv[1]
    output_path = sys.argv[2]

    # Load metadata
    metadata = load_json(input_path)
    nodes = metadata.get('nodes', [])

    if not nodes:
        print(f"Error: No nodes found in {input_path}")
        sys.exit(1)

    print(f"Loaded {len(nodes)} nodes from {input_path}")

    # Build tree
    tree = build_tree(nodes)

    # Compute stats
    stats = compute_tree_stats(tree)

    # Extract metadata
    source_file = metadata.get('input_path', input_path)
    model_unit = metadata.get('model_unit', 0)

    # Build output
    output = {
        'generator': 'scs_metadata',
        'source': source_file,
        'scs_file': metadata.get('output_path', ''),
        'model_unit': model_unit,
        'node_count': len(nodes),
        'stats': stats,
        'scene_tree': tree,
        'flat_nodes': [
            {
                'key': n.get('key', ''),
                'parent_key': n.get('parent_key', ''),
                'name': n.get('name', ''),
                'persistent_id': n.get('persistent_id', 0),
                'bbox_valid': n.get('standard_bbox_valid', False),
            }
            for n in nodes
        ],
    }

    # Write output
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"\nExtracted tree structure:")
    print(f"  Total nodes:  {stats['total_nodes']}")
    print(f"  Max depth:    {stats['max_depth']}")
    print(f"  Leaf nodes:   {stats['leaf_count']}")
    print(f"  Node types:   {stats['type_counts']}")
    if stats['total_bbox_min']:
        print(f"  Total bbox:   {stats['total_bbox_min']} → {stats['total_bbox_max']}")

    print(f"\nOutput written to: {output_path}")


if __name__ == '__main__':
    main()
